[[headers]]
for = "/*"
[headers.values]
  Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
  Content-Security-Policy = "default-src 'self'; img-src 'self'; script-src 'self' https://www.googletagmanager.com; style-src 'self' https://fonts.googleapis.com 'unsafe-inline'; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://la-pizz.onrender.com; frame-src 'self' https://www.google.com https://www.google.com/maps"
  X-Frame-Options = "SAMEORIGIN"
  X-Content-Type-Options = "nosniff"
  Referrer-Policy = "strict-origin-when-cross-origin"
  Permissions-Policy = "geolocation=(self), microphone=(), camera=()"
